---
ignore: |
  /nautobot_ssot_ipfabric/.devcontainer/
extends: "default"
rules:
  comments: "enable"
  empty-values: "enable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
