---
name: "ci"
on:  # yamllint disable
  - "push"
  - "pull_request"

jobs:
  lint:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_NAUTOBOT_SSOT_IPFABRIC: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v1"
      - name: "Copy credentials"
        run: "cp development/creds.example.env development/creds.env"
      - name: "Linting: black"
        run: "poetry run invoke black"
      - name: "Linting: bandit"
        run: "poetry run invoke bandit"
      - name: "Linting: pydocstyle"
        run: "poetry run invoke pydocstyle"
      - name: "Linting: flake8"
        run: "poetry run invoke flake8"
      - name: "Linting: yamllint"
        run: "poetry run invoke yamllint"
  unittest:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        nautobot-version: ["1.1.6"]
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_NAUTOBOT_SSOT_IPFABRIC_PYTHON_VER: "${{ matrix.python-version }}"
      INVOKE_NAUTOBOT_SSOT_IPFABRIC_NAUTOBOT_VER: "${{ matrix.nautobot-version }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v1"
      - name: "Copy credentials"
        run: "cp development/creds.example.env development/creds.env"
      - name: "Build Container"
        run: "poetry run invoke build"
      - name: "Run Tests"
        run: "poetry run invoke unittest"
    needs:
      - "lint"
